# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c42c5edea174cf40597479d71c42127ec17330315a5eab708db2ce0700c29717c47efbb0f56f172bd05150c8e3d537317747b2e948fbc43c369ecad5dfec3a0f

test:
  secret_key_base: 93c07d84435bb1639a4b4b2ed84b46f80578a098c680f1dca5269b5e2a7cab42cda143c98428ea6757204691d2e3bab253c57c6ed7a33d83ca74a61d1197a86b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
